minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: files
  region: us-east-1

spring:
  application:
    name: spring-boot-minio
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 4444

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
